appId: com.stopshorts.app
---
# Training Module E2E Test
# Tests navigating through training topics, articles, quizzes, and worksheets
#
# Prerequisites: None - uses demo mode skip if onboarding is shown

- launchApp

# Wait for app to fully load
- waitForAnimationToEnd

# Skip onboarding using demo mode if on welcome screen
- runFlow:
    when:
      visible: "始める"
    commands:
      - waitForAnimationToEnd
      # Tap on "デモモードでスキップ →" to skip entire onboarding
      - tapOn:
          text: ".*デモモードでスキップ.*"
      - waitForAnimationToEnd:
          timeout: 3000

# Now we should be on the main screen (Dashboard)
- waitForAnimationToEnd:
    timeout: 3000

# Navigate to Training Tab
# Note: Tab shows "training/index" due to i18n bug - using regex to match
- tapOn:
    text: ".*training.*"

- waitForAnimationToEnd

# Verify Training Screen
- assertVisible: "トレーニング"
- assertVisible: "科学的アプローチ"
# Other sections require scrolling - skip for now

# Open a topic
- tapOn: "習慣ループを理解する"

# Verify Topic Detail Screen
- assertVisible: "記事"
- assertVisible: "クイズ"
- assertVisible: "ワークシート"

# Open Article
- tapOn: "記事"
- assertVisible: "習慣の3つの要素"
- scrollUntilVisible:
    element: "次へ進む"
    direction: DOWN
- tapOn: "次へ進む"

# Quiz Phase
- waitForAnimationToEnd
- assertVisible: "クイズ"
- assertVisible: "習慣ループの理解度チェック"

# Answer first question
- tapOn: "きっかけ・ルーティン・報酬"

# Answer second question (may need scroll)
- tapOn: "ルーティンを別の行動に置き換える"

# Check answers (scroll to find button)
- scrollUntilVisible:
    element: "答え合わせ"
    direction: DOWN
    timeout: 10000
- tapOn: "答え合わせ"

# Note: Quiz results show checkmarks, no "正解" text
- waitForAnimationToEnd

# Continue to worksheet
- scrollUntilVisible:
    element: "次へ進む"
    direction: DOWN
    timeout: 10000
- tapOn: "次へ進む"

# Worksheet Phase
- waitForAnimationToEnd
- assertVisible: "ワークシート"
- assertVisible: "あなたの習慣ループを分析しよう"

# Tap on input field using placeholder text
- tapOn:
    text: ".*きっかけを書いてください.*"
# Note: Maestro doesn't support Japanese input, use ASCII
- inputText: "Bored at home scrolling"
- hideKeyboard
- tapOn: "回答を保存"

# Complete Phase
- waitForAnimationToEnd
- assertVisible:
    text: ".*トピック完了.*"
- tapOn: "トピック一覧に戻る"

# Verify back on list
- waitForAnimationToEnd
- assertVisible: "科学的アプローチ"
